import type { WalletIconKey } from "@oinc/api/wallet-appearance";
import {
  Banknote,
  Bitcoin,
  Briefcase,
  Building,
  Building2,
  Car,
  ChartLine,
  CircleDollarSign,
  Coins,
  CreditCard,
  Gem,
  Gift,
  GraduationCap,
  HandCoins,
  HeartPulse,
  House,
  Landmark,
  type LucideIcon,
  PiggyBank,
  Plane,
  Receipt,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Target,
  TrendingUp,
  Utensils,
  Vault,
  Wallet,
  WalletCards,
  Wine,
} from "lucide-react";

export const WALLET_ICON_COMPONENTS: Record<WalletIconKey, LucideIcon> = {
  wallet: Wallet,
  "piggy-bank": PiggyBank,
  landmark: Landmark,
  banknote: Banknote,
  "credit-card": CreditCard,
  coins: Coins,
  building: Building,
  "building-2": Building2,
  "wallet-cards": WalletCards,
  vault: Vault,
  "hand-coins": HandCoins,
  "circle-dollar-sign": CircleDollarSign,
  receipt: Receipt,
  gem: Gem,
  "trending-up": TrendingUp,
  briefcase: Briefcase,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  gift: Gift,
  car: Car,
  house: House,
  plane: Plane,
  "graduation-cap": GraduationCap,
  "heart-pulse": HeartPulse,
  utensils: Utensils,
  wine: Wine,
  shirt: Shirt,
  bitcoin: Bitcoin,
  "chart-line": ChartLine,
  target: Target,
};
