import type { CategoryIconKey } from "@oinc/api/category-appearance";
import {
  Baby,
  Banknote,
  Briefcase,
  Bus,
  Car,
  CircleDollarSign,
  Coins,
  Dog,
  Dumbbell,
  Film,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  HandCoins,
  HeartPulse,
  House,
  Landmark,
  type LucideIcon,
  Phone,
  PiggyBank,
  Plane,
  Receipt,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  TrendingUp,
  Utensils,
  Wifi,
  Wine,
  Wrench,
} from "lucide-react";

export const CATEGORY_ICON_COMPONENTS: Record<CategoryIconKey, LucideIcon> = {
  utensils: Utensils,
  "shopping-cart": ShoppingCart,
  "shopping-bag": ShoppingBag,
  car: Car,
  house: House,
  receipt: Receipt,
  "heart-pulse": HeartPulse,
  "graduation-cap": GraduationCap,
  plane: Plane,
  "gamepad-2": Gamepad2,
  film: Film,
  gift: Gift,
  wine: Wine,
  shirt: Shirt,
  dumbbell: Dumbbell,
  dog: Dog,
  baby: Baby,
  wrench: Wrench,
  phone: Phone,
  wifi: Wifi,
  fuel: Fuel,
  bus: Bus,
  briefcase: Briefcase,
  banknote: Banknote,
  "trending-up": TrendingUp,
  "hand-coins": HandCoins,
  "piggy-bank": PiggyBank,
  coins: Coins,
  "circle-dollar-sign": CircleDollarSign,
  landmark: Landmark,
};
